### ISSUE TITLE
Is it possible to derive for a field that has arbitrary string keys?

### ISSUE THREAD

**Issue by anentropic** [patricoferris/ppx_deriving_yaml#24]
I'm trying to model a YAML structure like:
```yaml
name: something
jobs:
  - <arbitrary name>:
    standard-key1: value
    standard-key2: value
  - <arbitrary name>:
    standard-key1: value
    standard-key2: value
```
I can achieve this serialized output by constructing my ocaml value directly from `` `O`` and `` `A`` literals.

But I would like to define a record type like:
```ocaml
type action = {
  name: string;
  jobs: (string * job) list;
}
[@@deriving yaml]
```

Is there a recipe for this in `ppx_deriving_yaml` currently?

ocaml-yaml defines `` `O of (string * value) list`` so I was hoping that `jobs: (string * job) list` would work, but it seems that the `(string * value)` tuples are serialized as a list instead of key-value object, so the yaml string comes out as:
```yaml
name: something
jobs:
  - - <arbitrary name>:
    - standard-key1: value
      standard-key2: value
  - - <arbitrary name>:
    - standard-key1: value
      standard-key2: value
```
I am new to OCaml so I apologise if I am missing something obvious that I've done wrong.

Thanks for this useful library!

(I get the same problem from my record type using `ppx_yojson_conv` and output as JSON too)

**Comment by patricoferris** [comment]
Hi @anentropic,

EDIT: Feel free to skip to the end, it's the best solution I think and one I might change my code to use if I ever find the time :))

Thanks for the kind words, glad someone is using the library besides me :)) There's no easy answer (that I can think of). This sounds very similar to something I had to deal with when encoding [Github actions into OCaml](https://github.com/patricoferris/opam-github-workflow/tree/main/lib). 

Essentially, afaict, there are two options. You could go completely "untyped" as you mentioned:

```ocaml
type t = { jobs : Yaml.value } [@@deriving yaml]

let () =
  let v : t =
    {
      jobs =
        `O
          [
            ( "my_name",
              `O [ ("key_1", `String "hello"); ("key_2", `String "world") ] );
          ];
    }
  in
  let y = to_yaml v in
  Yaml.pp Fmt.stdout y
``` 

At which point you are just hoping people use your library (or whatever you are building) correctly because they could put any Yaml they want in there. Note that the ppx is essentially working on an almost textual level, so it reads `Yaml.value` and applies the identity function (cf. https://github.com/patricoferris/ppx_deriving_yaml/blob/main/lib/value.ml#L20). I don't quite have the time to look into but maybe there could be other cases in there for the individual Yaml values so you could refine this to just the `` `O of (string * Yaml.value) list`` constructor? 

The second option is to force a user to define the types and provide them with the building blocks to at least build the right type, like I did for the Github workflow jobs. In this sense you get a little more type safety, you can still use `ppx_deriving_yaml` to do the tedious work at the cost of a user still being able to misuse the API: 

```ocaml
(* YOUR LIBRARY *)
module Lib = struct
  type job_body = { some_key : string } [@@deriving yaml]

  type 'a t = { jobs : 'a } [@@deriving yaml]
end

(* USER DEFINED *)
type jobs = { job_one : Lib.job_body; job_two : Lib.job_body } [@@deriving yaml]

type t = jobs Lib.t [@@deriving yaml]

let () =
  let v : t =
    {
      jobs =
        { job_one = { some_key = "Hello" }; job_two = { some_key = "World" } };
    }
  in
  let y = to_yaml v in
  Yaml.pp Fmt.stdout y
```

---

Actually, you've made me think quite a bit about this, and I think a much better solution is just to impose a type for your jobs and write the decoding and encoding functions explicitly. Something like: 

```ocaml
type job_body = { some_key : string } [@@deriving yaml]

type jobs = (string * job_body) list

let jobs_to_yaml jobs : Yaml.value =
  `A
    (List.map
       (fun (arb_name, body) -> `O [ (arb_name, job_body_to_yaml body) ])
       jobs)

let jobs_of_yaml (yml : Yaml.value) =
  let body (t : Yaml.value) =
    match t with
    | `O [ (arb_name, body) ] ->
        job_body_of_yaml body |> Rresult.R.get_ok |> fun body -> (arb_name, body)
    | _ -> assert false
  in
  match yml with `A lst -> Ok (List.map body lst) | _ -> assert false

type t = { jobs : jobs } [@@deriving yaml]

let () =
  let v : t =
    {
      jobs =
        [
          ("arbitrary-name", { some_key = "Hello" });
          ("another-name", { some_key = "World" });
        ];
    }
  in
  let y = to_yaml v in
  Yaml.pp Fmt.stdout y
```

Which gives: 

```yaml
jobs:                
- arbitrary-name:
    some_key: Hello
- another-name:
    some_key: World
```

without losing any of the type-safety 👍

**Comment by anentropic** [comment]
@patricoferris Thank you for your helpful detailed answer... I will take a while and digest it 😄 

I am curious about your work with GitHub Actions as you maybe recognised that is what I'm trying to do also... ~did you make any library for it?~ just found the link above 🤦 

Probably for my specific case it does not need to be as generic as I was thinking and I could define a record type with some hard-coded job names instead of modelling the abstract schema.

Your last example looks like what I was trying to achieve... thanks again!

**Comment by patricoferris** [comment]
Awesome, I'll close this for now. Feel free to open other issues if you have questions, the library I wrote is probably broken/incomplete but it is serving its purpose for now haha. Good luck :))
